### ISSUE TITLE
"syntax: { } vector syntax is discontinued" when interpolating template literals in Javascript

### ISSUE THREAD

**Issue by topolarity** [SimonDanisch/Bonito.jl#209]
```julia
app = App() do session, request
    width = 500; height = 500
    dom = DOM.div(width = width, height = height)
    Bonito.onload(session, dom, js"""
        function (container){
            var str = "Hello, world!";
            alert(`${test}`);
        }
    """)
    return dom
end
```

Gives an error:
```julia
ERROR: LoadError: syntax: { } vector syntax is discontinued around /home/topolarity/repos/julia/show_graph.jl:11
Stacktrace:
 [1] top-level scope
   @ ~/repos/julia/show_graph.jl:8
 [2] include(fname::String)
   @ Base.MainInclude ./client.jl:489
 [3] top-level scope
   @ REPL[9]:1
in expression starting at /home/topolarity/repos/julia/show_graph.jl:8
```

See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

**Comment by SimonDanisch** [comment]
I dont think we can make this work.
You can include the JS as a dependency via a `.js` file, or use any other string concatenation strategy ;)

**Comment by topolarity** [comment]
The warning seems to suggest that `${...}` always represents the discontinued vector syntax in Julia.

`$( ... )` and other variants are not used as a placeholder in Javascript, just the curly brace syntax (to my knowledge).

Is there a reason that can't be escaped from interpolation?
