### ISSUE TITLE
accessing query variables in Request

### ISSUE THREAD

**Issue by bjarthur** [SimonDanisch/Bonito.jl#219]
when i serve a website with Bonito, i'd like the user to be able to configure the generated HTML by appending "?var=val" to the end of the URL.  programmatically something like this would be convenient:

```
app = App() do session::Session
    query = session...   # var=val stored as a Dict or similar somewhere in the session Struct
    return DOM.div(query["var"])
end
```

currently i think this is not possible.

digging into the code, the query is stored in `request` [here](https://github.com/SimonDanisch/Bonito.jl/blob/master/src/HTTPServer/implementation.jl#L90) and subsequently further down the call stack in `context` [here](https://github.com/SimonDanisch/Bonito.jl/blob/master/src/app.jl#L121), but then is never stored.  i think the [definition](https://github.com/SimonDanisch/Bonito.jl/blob/master/src/types.jl#L158) of `Session` would need a new field to store this information.

does that make sense?  if so, i'm happy to work on a PR with some guidance.

**Comment by SimonDanisch** [comment]
There is:
```julia
app = App() do session::Session, request::HTTP.Request
    requested_path= request.path # There should be some query parsing tools somewhere in in URIs or HTTP.jl
    ...
end
```

**Comment by SimonDanisch** [comment]
I'm surprised that App isn't documented at all, I fuzzily remember writing docstrings for it^^ Maybe you could add a PR for that?

**Comment by bjarthur** [comment]
oh!  my bad.  App is documented, in two places, and i did read the docs when first learning Bonito, but then forgot:

```
julia> using Bonito

help?> App
search: App append! applicable isapprox swapproperty! apropos hasproperty replaceproperty!

  App(callback_or_dom; title="Bonito App")
  App((session, request) -> DOM.div(...))
  App((session::Session) -> DOM.div(...))
  App((request::HTTP.Request) -> DOM.div(...))
  App(() -> DOM.div(...))
  App(DOM.div(...))

  Usage:

  using Bonito
  app = App() do
      return DOM.div(DOM.h1("hello world"), js"""console.log('hello world')""")
  end

  If you depend on global observable, make sure to bind it to the session. This is pretty
  important, since every time you display the app, listeners will get registered to it, that
  will just continue staying there until your Julia process gets closed. bind_global prevents
  that by binding the observable to the life cycle of the session and cleaning up the state
  after the app isn't displayed anymore. If you serve the App via a Server, be aware, that
  those globals will be shared with everyone visiting the page, so possibly by many users
  concurrently.

  global some_observable = Observable("global hello world")
  App() do session::Session
      bound_global = bind_global(session, some_observable)
      return DOM.div(bound_global)
  end
```

perhaps it would be worthwhile adding an example which explicitly used Request.

**Comment by cstjean** [comment]
`request.url.path` is empty for me:

```julia
myapp = App(; title="MyApp") do session, request
    @show request.url
    @show request.url.path
```
yields
```julia
request.url = URI("")
request.url.path = ""
```
@bjarthur Does your code still work?

**Comment by cstjean** [comment]
`Bonito.HTTP.URIs.queryparams(request.target)` does not work on `http://localhost:9384?q=blah/`, but when serving it worked out. Thanks you!
