### ISSUE TITLE
`WGLMakie` plots not rendering over SSH

### ISSUE THREAD

**Issue by vpuri3** [SimonDanisch/Bonito.jl#230]
I am using Bonito + WGLMakie to view visualizations done on my remote machine. 
The issue I am facing is that WGLMakie plots are not rendering in my browser on my local machine.

Here's my workflow: I log into my remote machine with

```bash
$ ssh -L 8080:localhost:8700 remote-machine
```

and run the following Julia script.

```julia
julia> using Bonito, WGLMakie

julia> WGLMakie.activate!()

julia> isdefined(Main, :server) && close(server)

julia> app = App((sess, req) -> DOM.div(DOM.h1("Plot below"), lines(rand(10)), DOM.h1("Plot above")));

julia> server = Bonito.Server(app, "127.0.0.1", 8700);
```

The output on `http://localhost:8080` is
![Screenshot 2024-06-04 at 3 57 10 PM](https://github.com/SimonDanisch/Bonito.jl/assets/36345239/b4f1ad58-8e9b-4f79-be17-38de1d689e1f)

When I run the same script locally, I get the expected result:
![Screenshot 2024-06-04 at 4 00 01 PM](https://github.com/SimonDanisch/Bonito.jl/assets/36345239/bd32799f-4a41-4169-8031-da7c1a5782b6)

**Comment by AlexisRenchon** [comment]
you need a proxy_url https://simondanisch.github.io/Bonito.jl/stable/deployment.html 

`server = Bonito.Server(app, "127.0.0.1", 8700; proxy_url = "http://localhost:8080)`

**Comment by SimonDanisch** [comment]
Yeah that's it ;) Easier to just do `ssh -L 8080:localhost:8080`
